//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTest.WSRegistro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://CAISA_DEMO.org/")]
    [System.SerializableAttribute()]
    public partial class Usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoelectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoPatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoMatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechNacField;
        
        private int edadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pass1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pass2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pass3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correoelectronico {
            get {
                return this.correoelectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoelectronicoField, value) != true)) {
                    this.correoelectronicoField = value;
                    this.RaisePropertyChanged("correoelectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string apellidoPat {
            get {
                return this.apellidoPatField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoPatField, value) != true)) {
                    this.apellidoPatField = value;
                    this.RaisePropertyChanged("apellidoPat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string apellidoMat {
            get {
                return this.apellidoMatField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoMatField, value) != true)) {
                    this.apellidoMatField = value;
                    this.RaisePropertyChanged("apellidoMat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fechNac {
            get {
                return this.fechNacField;
            }
            set {
                if ((object.ReferenceEquals(this.fechNacField, value) != true)) {
                    this.fechNacField = value;
                    this.RaisePropertyChanged("fechNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                if ((this.edadField.Equals(value) != true)) {
                    this.edadField = value;
                    this.RaisePropertyChanged("edad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pass1 {
            get {
                return this.pass1Field;
            }
            set {
                if ((object.ReferenceEquals(this.pass1Field, value) != true)) {
                    this.pass1Field = value;
                    this.RaisePropertyChanged("pass1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string pass2 {
            get {
                return this.pass2Field;
            }
            set {
                if ((object.ReferenceEquals(this.pass2Field, value) != true)) {
                    this.pass2Field = value;
                    this.RaisePropertyChanged("pass2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string pass3 {
            get {
                return this.pass3Field;
            }
            set {
                if ((object.ReferenceEquals(this.pass3Field, value) != true)) {
                    this.pass3Field = value;
                    this.RaisePropertyChanged("pass3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Registro de UsuarioSoap", Namespace="http://CAISA_DEMO.org/", ConfigurationName="WSRegistro.RegistrodeUsuarioSoap")]
    public interface RegistrodeUsuarioSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://CAISA_DEMO.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/Ingreso", ReplyAction="*")]
        WebAppTest.WSRegistro.IngresoResponse Ingreso(WebAppTest.WSRegistro.IngresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/Ingreso", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.IngresoResponse> IngresoAsync(WebAppTest.WSRegistro.IngresoRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://CAISA_DEMO.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/CapturaUsuario", ReplyAction="*")]
        WebAppTest.WSRegistro.CapturaUsuarioResponse CapturaUsuario(WebAppTest.WSRegistro.CapturaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/CapturaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.CapturaUsuarioResponse> CapturaUsuarioAsync(WebAppTest.WSRegistro.CapturaUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://CAISA_DEMO.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/ActualizaUsuario", ReplyAction="*")]
        WebAppTest.WSRegistro.ActualizaUsuarioResponse ActualizaUsuario(WebAppTest.WSRegistro.ActualizaUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/ActualizaUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.ActualizaUsuarioResponse> ActualizaUsuarioAsync(WebAppTest.WSRegistro.ActualizaUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://CAISA_DEMO.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/BorraUsuario", ReplyAction="*")]
        WebAppTest.WSRegistro.BorraUsuarioResponse BorraUsuario(WebAppTest.WSRegistro.BorraUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/BorraUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.BorraUsuarioResponse> BorraUsuarioAsync(WebAppTest.WSRegistro.BorraUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://CAISA_DEMO.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/EnviarCorreo", ReplyAction="*")]
        WebAppTest.WSRegistro.EnviarCorreoResponse EnviarCorreo(WebAppTest.WSRegistro.EnviarCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CAISA_DEMO.org/EnviarCorreo", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.EnviarCorreoResponse> EnviarCorreoAsync(WebAppTest.WSRegistro.EnviarCorreoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ingreso", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.IngresoRequestBody Body;
        
        public IngresoRequest() {
        }
        
        public IngresoRequest(WebAppTest.WSRegistro.IngresoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class IngresoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public IngresoRequestBody() {
        }
        
        public IngresoRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresoResponse", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.IngresoResponseBody Body;
        
        public IngresoResponse() {
        }
        
        public IngresoResponse(WebAppTest.WSRegistro.IngresoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class IngresoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebAppTest.WSRegistro.Usuarios[] IngresoResult;
        
        public IngresoResponseBody() {
        }
        
        public IngresoResponseBody(WebAppTest.WSRegistro.Usuarios[] IngresoResult) {
            this.IngresoResult = IngresoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapturaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapturaUsuario", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.CapturaUsuarioRequestBody Body;
        
        public CapturaUsuarioRequest() {
        }
        
        public CapturaUsuarioRequest(WebAppTest.WSRegistro.CapturaUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class CapturaUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string apePa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string apeMa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string domicilio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string fechNac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string pass1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pass2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string pass3;
        
        public CapturaUsuarioRequestBody() {
        }
        
        public CapturaUsuarioRequestBody(string usuario, string pass, string correo, string nombre, string apePa, string apeMa, string domicilio, string fechNac, string edad, string telefono, string pass1, string pass2, string pass3) {
            this.usuario = usuario;
            this.pass = pass;
            this.correo = correo;
            this.nombre = nombre;
            this.apePa = apePa;
            this.apeMa = apeMa;
            this.domicilio = domicilio;
            this.fechNac = fechNac;
            this.edad = edad;
            this.telefono = telefono;
            this.pass1 = pass1;
            this.pass2 = pass2;
            this.pass3 = pass3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CapturaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CapturaUsuarioResponse", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.CapturaUsuarioResponseBody Body;
        
        public CapturaUsuarioResponse() {
        }
        
        public CapturaUsuarioResponse(WebAppTest.WSRegistro.CapturaUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class CapturaUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CapturaUsuarioResult;
        
        public CapturaUsuarioResponseBody() {
        }
        
        public CapturaUsuarioResponseBody(string CapturaUsuarioResult) {
            this.CapturaUsuarioResult = CapturaUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizaUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizaUsuario", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.ActualizaUsuarioRequestBody Body;
        
        public ActualizaUsuarioRequest() {
        }
        
        public ActualizaUsuarioRequest(WebAppTest.WSRegistro.ActualizaUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class ActualizaUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string apePa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string apeMa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string domicilio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string fechNac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string pass1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string pass2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string pass3;
        
        public ActualizaUsuarioRequestBody() {
        }
        
        public ActualizaUsuarioRequestBody(int id, string usuario, string pass, string correo, string nombre, string apePa, string apeMa, string domicilio, string fechNac, string edad, string telefono, string pass1, string pass2, string pass3) {
            this.id = id;
            this.usuario = usuario;
            this.pass = pass;
            this.correo = correo;
            this.nombre = nombre;
            this.apePa = apePa;
            this.apeMa = apeMa;
            this.domicilio = domicilio;
            this.fechNac = fechNac;
            this.edad = edad;
            this.telefono = telefono;
            this.pass1 = pass1;
            this.pass2 = pass2;
            this.pass3 = pass3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizaUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizaUsuarioResponse", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.ActualizaUsuarioResponseBody Body;
        
        public ActualizaUsuarioResponse() {
        }
        
        public ActualizaUsuarioResponse(WebAppTest.WSRegistro.ActualizaUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class ActualizaUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActualizaUsuarioResult;
        
        public ActualizaUsuarioResponseBody() {
        }
        
        public ActualizaUsuarioResponseBody(string ActualizaUsuarioResult) {
            this.ActualizaUsuarioResult = ActualizaUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorraUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorraUsuario", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.BorraUsuarioRequestBody Body;
        
        public BorraUsuarioRequest() {
        }
        
        public BorraUsuarioRequest(WebAppTest.WSRegistro.BorraUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class BorraUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        public BorraUsuarioRequestBody() {
        }
        
        public BorraUsuarioRequestBody(int id, string usuario, string pass) {
            this.id = id;
            this.usuario = usuario;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BorraUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BorraUsuarioResponse", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.BorraUsuarioResponseBody Body;
        
        public BorraUsuarioResponse() {
        }
        
        public BorraUsuarioResponse(WebAppTest.WSRegistro.BorraUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class BorraUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BorraUsuarioResult;
        
        public BorraUsuarioResponseBody() {
        }
        
        public BorraUsuarioResponseBody(string BorraUsuarioResult) {
            this.BorraUsuarioResult = BorraUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreo", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.EnviarCorreoRequestBody Body;
        
        public EnviarCorreoRequest() {
        }
        
        public EnviarCorreoRequest(WebAppTest.WSRegistro.EnviarCorreoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class EnviarCorreoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        public EnviarCorreoRequestBody() {
        }
        
        public EnviarCorreoRequestBody(string user, string correo, string pass) {
            this.user = user;
            this.correo = correo;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarCorreoResponse", Namespace="http://CAISA_DEMO.org/", Order=0)]
        public WebAppTest.WSRegistro.EnviarCorreoResponseBody Body;
        
        public EnviarCorreoResponse() {
        }
        
        public EnviarCorreoResponse(WebAppTest.WSRegistro.EnviarCorreoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://CAISA_DEMO.org/")]
    public partial class EnviarCorreoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviarCorreoResult;
        
        public EnviarCorreoResponseBody() {
        }
        
        public EnviarCorreoResponseBody(string EnviarCorreoResult) {
            this.EnviarCorreoResult = EnviarCorreoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrodeUsuarioSoapChannel : WebAppTest.WSRegistro.RegistrodeUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrodeUsuarioSoapClient : System.ServiceModel.ClientBase<WebAppTest.WSRegistro.RegistrodeUsuarioSoap>, WebAppTest.WSRegistro.RegistrodeUsuarioSoap {
        
        public RegistrodeUsuarioSoapClient() {
        }
        
        public RegistrodeUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrodeUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrodeUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrodeUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppTest.WSRegistro.IngresoResponse WebAppTest.WSRegistro.RegistrodeUsuarioSoap.Ingreso(WebAppTest.WSRegistro.IngresoRequest request) {
            return base.Channel.Ingreso(request);
        }
        
        public WebAppTest.WSRegistro.Usuarios[] Ingreso(string usuario) {
            WebAppTest.WSRegistro.IngresoRequest inValue = new WebAppTest.WSRegistro.IngresoRequest();
            inValue.Body = new WebAppTest.WSRegistro.IngresoRequestBody();
            inValue.Body.usuario = usuario;
            WebAppTest.WSRegistro.IngresoResponse retVal = ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).Ingreso(inValue);
            return retVal.Body.IngresoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.IngresoResponse> WebAppTest.WSRegistro.RegistrodeUsuarioSoap.IngresoAsync(WebAppTest.WSRegistro.IngresoRequest request) {
            return base.Channel.IngresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppTest.WSRegistro.IngresoResponse> IngresoAsync(string usuario) {
            WebAppTest.WSRegistro.IngresoRequest inValue = new WebAppTest.WSRegistro.IngresoRequest();
            inValue.Body = new WebAppTest.WSRegistro.IngresoRequestBody();
            inValue.Body.usuario = usuario;
            return ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).IngresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppTest.WSRegistro.CapturaUsuarioResponse WebAppTest.WSRegistro.RegistrodeUsuarioSoap.CapturaUsuario(WebAppTest.WSRegistro.CapturaUsuarioRequest request) {
            return base.Channel.CapturaUsuario(request);
        }
        
        public string CapturaUsuario(string usuario, string pass, string correo, string nombre, string apePa, string apeMa, string domicilio, string fechNac, string edad, string telefono, string pass1, string pass2, string pass3) {
            WebAppTest.WSRegistro.CapturaUsuarioRequest inValue = new WebAppTest.WSRegistro.CapturaUsuarioRequest();
            inValue.Body = new WebAppTest.WSRegistro.CapturaUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            inValue.Body.correo = correo;
            inValue.Body.nombre = nombre;
            inValue.Body.apePa = apePa;
            inValue.Body.apeMa = apeMa;
            inValue.Body.domicilio = domicilio;
            inValue.Body.fechNac = fechNac;
            inValue.Body.edad = edad;
            inValue.Body.telefono = telefono;
            inValue.Body.pass1 = pass1;
            inValue.Body.pass2 = pass2;
            inValue.Body.pass3 = pass3;
            WebAppTest.WSRegistro.CapturaUsuarioResponse retVal = ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).CapturaUsuario(inValue);
            return retVal.Body.CapturaUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.CapturaUsuarioResponse> WebAppTest.WSRegistro.RegistrodeUsuarioSoap.CapturaUsuarioAsync(WebAppTest.WSRegistro.CapturaUsuarioRequest request) {
            return base.Channel.CapturaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppTest.WSRegistro.CapturaUsuarioResponse> CapturaUsuarioAsync(string usuario, string pass, string correo, string nombre, string apePa, string apeMa, string domicilio, string fechNac, string edad, string telefono, string pass1, string pass2, string pass3) {
            WebAppTest.WSRegistro.CapturaUsuarioRequest inValue = new WebAppTest.WSRegistro.CapturaUsuarioRequest();
            inValue.Body = new WebAppTest.WSRegistro.CapturaUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            inValue.Body.correo = correo;
            inValue.Body.nombre = nombre;
            inValue.Body.apePa = apePa;
            inValue.Body.apeMa = apeMa;
            inValue.Body.domicilio = domicilio;
            inValue.Body.fechNac = fechNac;
            inValue.Body.edad = edad;
            inValue.Body.telefono = telefono;
            inValue.Body.pass1 = pass1;
            inValue.Body.pass2 = pass2;
            inValue.Body.pass3 = pass3;
            return ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).CapturaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppTest.WSRegistro.ActualizaUsuarioResponse WebAppTest.WSRegistro.RegistrodeUsuarioSoap.ActualizaUsuario(WebAppTest.WSRegistro.ActualizaUsuarioRequest request) {
            return base.Channel.ActualizaUsuario(request);
        }
        
        public string ActualizaUsuario(int id, string usuario, string pass, string correo, string nombre, string apePa, string apeMa, string domicilio, string fechNac, string edad, string telefono, string pass1, string pass2, string pass3) {
            WebAppTest.WSRegistro.ActualizaUsuarioRequest inValue = new WebAppTest.WSRegistro.ActualizaUsuarioRequest();
            inValue.Body = new WebAppTest.WSRegistro.ActualizaUsuarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            inValue.Body.correo = correo;
            inValue.Body.nombre = nombre;
            inValue.Body.apePa = apePa;
            inValue.Body.apeMa = apeMa;
            inValue.Body.domicilio = domicilio;
            inValue.Body.fechNac = fechNac;
            inValue.Body.edad = edad;
            inValue.Body.telefono = telefono;
            inValue.Body.pass1 = pass1;
            inValue.Body.pass2 = pass2;
            inValue.Body.pass3 = pass3;
            WebAppTest.WSRegistro.ActualizaUsuarioResponse retVal = ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).ActualizaUsuario(inValue);
            return retVal.Body.ActualizaUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.ActualizaUsuarioResponse> WebAppTest.WSRegistro.RegistrodeUsuarioSoap.ActualizaUsuarioAsync(WebAppTest.WSRegistro.ActualizaUsuarioRequest request) {
            return base.Channel.ActualizaUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppTest.WSRegistro.ActualizaUsuarioResponse> ActualizaUsuarioAsync(int id, string usuario, string pass, string correo, string nombre, string apePa, string apeMa, string domicilio, string fechNac, string edad, string telefono, string pass1, string pass2, string pass3) {
            WebAppTest.WSRegistro.ActualizaUsuarioRequest inValue = new WebAppTest.WSRegistro.ActualizaUsuarioRequest();
            inValue.Body = new WebAppTest.WSRegistro.ActualizaUsuarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            inValue.Body.correo = correo;
            inValue.Body.nombre = nombre;
            inValue.Body.apePa = apePa;
            inValue.Body.apeMa = apeMa;
            inValue.Body.domicilio = domicilio;
            inValue.Body.fechNac = fechNac;
            inValue.Body.edad = edad;
            inValue.Body.telefono = telefono;
            inValue.Body.pass1 = pass1;
            inValue.Body.pass2 = pass2;
            inValue.Body.pass3 = pass3;
            return ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).ActualizaUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppTest.WSRegistro.BorraUsuarioResponse WebAppTest.WSRegistro.RegistrodeUsuarioSoap.BorraUsuario(WebAppTest.WSRegistro.BorraUsuarioRequest request) {
            return base.Channel.BorraUsuario(request);
        }
        
        public string BorraUsuario(int id, string usuario, string pass) {
            WebAppTest.WSRegistro.BorraUsuarioRequest inValue = new WebAppTest.WSRegistro.BorraUsuarioRequest();
            inValue.Body = new WebAppTest.WSRegistro.BorraUsuarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            WebAppTest.WSRegistro.BorraUsuarioResponse retVal = ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).BorraUsuario(inValue);
            return retVal.Body.BorraUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.BorraUsuarioResponse> WebAppTest.WSRegistro.RegistrodeUsuarioSoap.BorraUsuarioAsync(WebAppTest.WSRegistro.BorraUsuarioRequest request) {
            return base.Channel.BorraUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppTest.WSRegistro.BorraUsuarioResponse> BorraUsuarioAsync(int id, string usuario, string pass) {
            WebAppTest.WSRegistro.BorraUsuarioRequest inValue = new WebAppTest.WSRegistro.BorraUsuarioRequest();
            inValue.Body = new WebAppTest.WSRegistro.BorraUsuarioRequestBody();
            inValue.Body.id = id;
            inValue.Body.usuario = usuario;
            inValue.Body.pass = pass;
            return ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).BorraUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebAppTest.WSRegistro.EnviarCorreoResponse WebAppTest.WSRegistro.RegistrodeUsuarioSoap.EnviarCorreo(WebAppTest.WSRegistro.EnviarCorreoRequest request) {
            return base.Channel.EnviarCorreo(request);
        }
        
        public string EnviarCorreo(string user, string correo, string pass) {
            WebAppTest.WSRegistro.EnviarCorreoRequest inValue = new WebAppTest.WSRegistro.EnviarCorreoRequest();
            inValue.Body = new WebAppTest.WSRegistro.EnviarCorreoRequestBody();
            inValue.Body.user = user;
            inValue.Body.correo = correo;
            inValue.Body.pass = pass;
            WebAppTest.WSRegistro.EnviarCorreoResponse retVal = ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).EnviarCorreo(inValue);
            return retVal.Body.EnviarCorreoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebAppTest.WSRegistro.EnviarCorreoResponse> WebAppTest.WSRegistro.RegistrodeUsuarioSoap.EnviarCorreoAsync(WebAppTest.WSRegistro.EnviarCorreoRequest request) {
            return base.Channel.EnviarCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebAppTest.WSRegistro.EnviarCorreoResponse> EnviarCorreoAsync(string user, string correo, string pass) {
            WebAppTest.WSRegistro.EnviarCorreoRequest inValue = new WebAppTest.WSRegistro.EnviarCorreoRequest();
            inValue.Body = new WebAppTest.WSRegistro.EnviarCorreoRequestBody();
            inValue.Body.user = user;
            inValue.Body.correo = correo;
            inValue.Body.pass = pass;
            return ((WebAppTest.WSRegistro.RegistrodeUsuarioSoap)(this)).EnviarCorreoAsync(inValue);
        }
    }
}
